### ISSUE TITLE
__init__() takes at least 8 arguments (7 given)

### ISSUE THREAD

**Issue by cslamar** [fabfuel/ecs-deploy#35] opened 2017-10-09 17:59 UTC
Everytime I do a deploy I get the following response:
`__init__() takes at least 8 arguments (7 given)`

command ran is: `ecs deploy test-cluster test-service` . Though I've tried multiple combinations of different options flags, but it always returns the error above.

Any insight would be great, Thanks.

**Comment by fabfuel** [comment] 2017-10-10 04:56
Hi @cslamar,

which version do you use?
```
pip freeze | grep ecs
```

Best
Fabian

**Comment by cslamar** [comment] 2017-10-10 12:46
ecs-deploy==1.3.1

**Comment by fabfuel** [comment] 2017-10-10 13:05
I can't reproduce this. Did you already try to re-install?

**Comment by fabfuel** [comment] 2017-10-10 13:05
The command you wrote above should work

**Comment by cslamar** [comment] 2017-10-10 13:07
I've tried both v1.3.1 and the HEAD of the repo.  Are there any other variables ecs is take in, or are "assumed"?  I'll try again on a fresh machine this afternoon.  Thanks for the response

**Comment by cslamar** [comment] 2017-10-12 01:14
Just to follow up.  I've reinstalled v1.3.1 on a few machines with the same error.  So I install v1.2.0 and the error went away.  Don't know if that shines any light on it, but thought I'd bring it up.

**Comment by Thussubasa** [comment] 2017-10-12 21:15
I had same issue, and after changed for v1.2.0,  worked for me.

**Comment by fabfuel** [comment] 2017-10-13 05:42
Would you please paste a full `pip freeze` of your environment? What Python version do you use?
I will try to reproduce it, so far I wasn't able to.

**Comment by fabfuel** [comment] 2017-10-22 08:15
Hi @cslamar & @Thussubasa,

I just released version 1.4.0 which includes more explicit error handling:
https://github.com/fabfuel/ecs-deploy/releases/tag/1.4.0

Do you still have the same issue with the new version?

Best
Fabian

**Comment by cslamar** [comment] 2017-10-22 18:29
Hi
  I'm still getting the same issue, but with a stack trace now

```
ecs deploy test-cluster test-service
Traceback (most recent call last):
  File "/Users/chris/.pyenv/versions/gp/bin/ecs", line 11, in <module>
    load_entry_point('ecs-deploy==1.4.1', 'console_scripts', 'ecs')()
  File "/Users/chris/.pyenv/versions/3.6.2/envs/gp/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chris/.pyenv/versions/3.6.2/envs/gp/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/chris/.pyenv/versions/3.6.2/envs/gp/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chris/.pyenv/versions/3.6.2/envs/gp/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chris/.pyenv/versions/3.6.2/envs/gp/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/chris/.pyenv/versions/3.6.2/envs/gp/lib/python3.6/site-packages/ecs_deploy/cli.py", line 65, in deploy
    td = get_task_definition(deployment, task)
  File "/Users/chris/.pyenv/versions/3.6.2/envs/gp/lib/python3.6/site-packages/ecs_deploy/cli.py", line 259, in get_task_definition
    task_definition = action.get_current_task_definition(action.service)
  File "/Users/chris/.pyenv/versions/3.6.2/envs/gp/lib/python3.6/site-packages/ecs_deploy/ecs.py", line 357, in get_current_task_definition
    return self.get_task_definition(service.task_definition)
  File "/Users/chris/.pyenv/versions/3.6.2/envs/gp/lib/python3.6/site-packages/ecs_deploy/ecs.py", line 365, in get_task_definition
    **task_definition_payload[u'taskDefinition']
TypeError: __init__() missing 1 required positional argument: 'requiresAttributes'
```

This is my `pip freeze` as well.

```
boto3==1.4.7
botocore==1.7.33
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
docutils==0.14
ecs-deploy==1.4.1
future==0.16.0
futures==3.1.1
idna==2.6
jmespath==0.9.3
python-dateutil==2.6.1
requests==2.18.4
s3transfer==0.1.11
six==1.11.0
urllib3==1.22
```

Tried with a fresh env of both python 2.7.13 and 3.6.3

Please let me know if you'd like more info or testing

Thanks!

**Comment by fabfuel** [comment] 2017-10-23 05:18
Thanks @cslamar, this was very helpful.
My environment was exactly the same, but it turned out, that the task definition response from AWS ECS does not always contain all properties. This should be fixed with hotfix `1.4.2`. You can install it from source here: 
```
pip install git+https://github.com/fabfuel/ecs-deploy.git@hotfix/1.4.2
```
But i will also publish the fix on PyPI soon.

Can you confirm, that it works not?

Best
Fabian

**Comment by fabfuel** [comment] 2017-10-23 05:49
The new version is available on PyPI now.

**Comment by cslamar** [comment] 2017-10-24 16:06
Fabian,
  Did some basic tests with 1.4.2-hotfix.  Everything i've tried works as excepted!  Thanks very much for the work!

Cheers,
--Chris

**Closed** 2017-10-24 17:28 UTC
Labels: bug
