### ISSUE TITLE
Fargate not supported

### ISSUE THREAD

**Issue by proggeramlug** [fabfuel/ecs-deploy#50] opened 2017-12-20 01:46 UTC
Tasks that support Fargate are not properly copied.

**Comment by fabfuel** [comment] 2017-12-20 05:18
Yes, Fargate is currently not supported. 

The introduction of Fargate broke ecs-deploy, because there are/were inconsistencies in the ECS API. The fetched task definition already included a new `compatibilities` parameter (which currently is `EC2` or `Fargate`), but it was not possible to register the same task definition without modifications.

Therefore, hotfix 1.4.3 explicitly excluded the `compatibilities` parameter when registering a new task definition revision: https://github.com/fabfuel/ecs-deploy/releases/tag/1.4.3

I'm not sure yet, if in the mean time this is fixed generally or if this depends on the region, as Fargate is only supported in us-east-1 at the moment.

I will have another look into this soon.

Best
Fabian

**Comment by haimari** [comment] 2017-12-21 12:41
Hello, Just mentioning that supporting fargate, even only in us-east-1 will be helpful for me too.

**Comment by proggeramlug** [comment] 2018-03-13 00:04
Any update here?

**Comment by fabfuel** [comment] 2018-04-28 04:53
Hi there!

I just tested a deployment on a Fargate cluster, which worked normally.
The new task definition is created with:
```
  "compatibilities": [
    "EC2",
    "FARGATE"
  ],
```

Which problems exactly do you have with your Fargate clusters?

Best
Fabian

**Comment by alexmbird** [comment] 2018-04-28 06:42
Hello there, thanks for getting back to me.

I was getting the following error:

```
$ pip install ecs-deploy
$ ecs deploy --region ${AWS_REGION} ${CLUSTER_NAME} ${SERVICE_NAME} --tag ${CI_COMMIT_SHA}
Unknown task definition arn: arn:aws:ecs:us-east-1:12345678:task-definition/my-task-def:3
```

In the end I worked around the problem by using `aws ecs` directly...

```
- aws ecs update-service
    --force-new-deployment
    --region ${AWS_REGION}
    --cluster ${CLUSTER_NAME}
    --service ${SERVICE_NAME} 
    --task-definition ${FAMILY_NAME}
```

**Comment by shredding** [comment] 2018-05-04 13:47
I receive

```
botocore.errorfactory.ClientException: An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Invalid setting for container 'web'. At least one of 'memory' or 'memoryReservation' must be specified
``

I have it specified on the task definition, but not on the container as this is no longer required by fargate:

```
resource "aws_ecs_task_definition" "web" {
  family                   = "${var.environment}_web"
  container_definitions    = "${data.template_file.web_task.rendered}"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "512"
  memory                   = "2048"
  execution_role_arn       = "${aws_iam_role.ecs_execution_role.arn}"
  task_role_arn            = "${aws_iam_role.ecs_execution_role.arn}"
}```

**Comment by Ancient123** [comment] 2018-06-28 17:06
I am using this without issue now with Fargate. @fabfuel is this still a problem or can this issue be closed?

**Comment by fabfuel** [comment] 2018-06-29 05:05
I also can not reproduce any issues with Fargate, which means it is generally working.
The issue mentioned by @alexmbird seemed to have other root.

I need to revalidate the error which @shredding mentioned, but this might only be happing if the memory limits are not defined per container. I will check this again.

Best
Fabian

**Comment by shredding** [comment] 2018-06-29 06:38
I'll try again today.

**Comment by squaresurf** [comment] 2018-08-10 23:18
I was able to successfully deploy a new task to Fargate. Unfortunately though, run task does not work since Fargate requires a NetworkConfiguration for setups that use `awsvpc` (i.e. all Fargate tasks).

```
An error occurred (InvalidParameterException) when calling the RunTask operation: Network Configuration must be provided when networkMode 'awsvpc' is specified.
```

@fabfuel should I create a new issue to track `ecs run ...` issues with Fargate?

**Comment by alanepontes** [comment] 2018-08-24 14:39
Just want to +1 @squaresurf. I get the same error too.

`An error occurred (InvalidParameterException) when calling the RunTask operation: Network Configuration must be provided when networkMode 'awsvpc' is specified.`

**Comment by fabfuel** [comment] 2018-08-24 16:47
@squaresurf, yes please create e new issue for that, as the "run task" action is independent from the service deployment.

**Comment by fabfuel** [comment] 2018-08-24 16:48
As there are confirmed successful usages of `ecs-deploy` with Fargate, I will close this issue for now.

**Closed by fabfuel** 2018-08-24 16:48 UTC

**Comment by squaresurf** [comment] 2018-09-01 23:02
@fabfuel I created #61. I'm sorry it took me so long.
